---
- name: GPG keys imported
  rpm_key: key="https://packages.elastic.co/GPG-KEY-elasticsearch"
  tags: elastic

- name: Elasticsearch repository at /etc/yum.repos.d/
  template: src="elasticsearch.repo" dest="/etc/yum.repos.d/elasticsearch.repo"
  tags: elastic

- name: Packages installed
  yum: name="{{ item }}" state="installed"
  with_items:
  - "java-1.8.0-openjdk"
  - "elasticsearch"
  tags: elastic

- name: Elasticsearch server is running
  service: name="elasticsearch" state="running" enabled="yes"
  tags: elastic
...
