  - name: WWW | clone repo
    git: repo="https://github.com/webarchivCZ/WWW.git"
         dest="/var/www/html/"

  - name: WWW | log directory is created
    file: path="/var/www/html/log" state="directory" owner="apache" group="apache"
  
  - name: WWW | temp directory is created
    file: path="/var/www/html/temp" state="directory" owner="apache" group="apache"

  - name: WWW | configuratiom for WWW
    copy: src="templates/config.product.neon" dest="/var/www/html/app/config/config.product.neon"

  - name: WWW | AllowOveride All in /var/www/html
    copy: src="templates/webarchiv_cz.conf" dest="/etc/httpd/conf.d/"

  - name: WWW | PHP is installed
    yum: name="php" state="installed"

  - name: WWW | PHP PDO is installed
    yum: name="php-pdo" state="installed"

  - name: WWW | PHP MySQL is installed
    yum: name="php-mysql" state="installed"
  
  - name: WWW | PHP Internationalization is installed
    yum: name="php-intl" state="installed"

  - name: WWW | PHP Multibyte String is installed
    yum: name="php-mbstring" state="installed"

  - name: WWW | Restart apache
    service: name="httpd" state="restarted"
