  - name: WWW | clone repo
    git: repo="https://github.com/webarchivCZ/WWW.git"
         dest="{{ apache_www }}"
         update="yes"

  - name: WWW | log directory is created
    file: 
      path: "{{ item }}" 
      state: "directory" 
      owner: "apache" 
      group: "apache"
      recurse: "yes"
      mode: "g+w"
    with_items:
      -  "{{ apache_www }}/log"
      -  "{{ apache_www }}/temp"
      -  "{{ apache_www }}"
  
  - name: WWW | configuratiom for WWW
    copy: 
      src: "templates/config.product.neon" 
      dest: "{{ apache_www }}/app/config/config.product.neon"
      owner: "apache"
      group: "apache"

  - name: WWW | PHP and modules are installed
    yum: name="{{ item }}" state="installed"
    with_items: 
      - "php"
      - "php-pdo"
      - "php-mysql"
      - "php-intl"
      - "php-mbstring"
    notify: restart apache
