  - name: Server and client are installed
    yum: name="{{ item }}"
    with_items:
    - postgresql
    - postgresql-server

  - name: Default Db is initalized
    command: service postgresql initdb
             creates="/var/lib/pgsql/data/postgresql.conf"
  
  - name: Server is running
    service: name="postgresql" state="started" enabled="yes"
