---
- hosts: all
  tasks:
  - name: NTP is installed
    yum: name=ntp state=installed

  - name: NTP daemon is running
    service: name=ntpd state=started enabled=yes

  - name: Git is always good
    yum: name=git state=installed

  - name: Set timezone to Europe/Prague | CET
    when: ansible_date_time.tz != 'CET'
    command: timedatectl set-timezone Europe/Prague
    tags: tz

  - name: Set admin group
    group: name=admin state=present

  - name: Set user for Rudolf Kreibich
    user: name=rudolf group=admin groups=wheel createhome=yes comment='Rudolf Kreibich' password="{{ item }}"
    with_file:
    - ../shared/encrypted/rudolf

  - name: Set public key for Rudolf Kreibich
    authorized_key: user=rudolf key="{{ item }}"
    with_file:
    - ../shared/public_keys/rudolf

  - name: Set user Bystroushaak
    user: name=bystroushaak group=admin groups=wheel createhome=yes comment='J.S.'

  - name: Set public key for Bystroushaak
    authorized_key: user=bystroushaak key="{{ item }}"
    with_file:
    - ../shared/public_keys/bystroushaak

  - name: Set user for Jaroslav Kvasnica
    user: name=jara group=admin groups=wheel createhome=yes comment='Jaroslav Kvasnica'


- hosts: db
  tasks:
  - name: Maria DB is installed
    yum: name=mariadb state=installed

- hosts: sentry
  tasks:
  - name: PostgreSQL is installed
    yum: name=postgresql state=installed

  - name: Docker is installed
    yum: name=docker state=installed

- hosts: seeder
  tasks:
  - name: Docker is installed
    yum: name=docker state=installed
  
  - name: Docker is running
    service: name=docker state=started enabled=yes
