  - name: Create users
    user: 
      name="{{ item.name }}" 
      groups="{{ item.groups}}" 
      createhome="yes" 
      comment="{{ item.comment }}" 
      password="{{ item.password }}"
    with_items: "{{admins}}"
    
      
  - name: Set public keys
    authorized_key: user="{{ item.name }}" key="{{ item.public_keys }}"
    with_items: "{{admins}}"
