  - name: Install beloved packeges
    yum: name="{{ item }}" state="installed"
    with_items:
      - "ntp"  # Time matters.
      - "unzip" # Ansible enjoys unzip
      - "vim" # Everybody loves vim!
      - "git" # Heart of everything

  - name: NTP daemon is running
    service: name=ntpd state=started enabled=yes

  - name: Set timezone to Europe/Prague | CET
    when: ansible_date_time.tz != 'CET'
    command: timedatectl set-timezone Europe/Prague
    tags: tz
