  - name: NTP is installed
    yum: name=ntp state=installed

  - name: NTP daemon is running
    service: name=ntpd state=started enabled=yes

  - name: Git is always good
    yum: name=git state=installed

  - name: Set timezone to Europe/Prague | CET
    when: ansible_date_time.tz != 'CET'
    command: timedatectl set-timezone Europe/Prague
    tags: tz

  - name: Ansible | Ansible needs unzip to extract archives
    yum: name="unzip" state="installed"
