---
- name: Add EPEL repository to yum
  yum:
    name: epel-release
    state: present
  tags: supervisor

- name: Install supervisord
  yum:
    name: supervisor
    state: present
  tags: supervisor

- name: Deploy supervisord.conf
  template:
    src: supervisord.conf.j2
    dest: /etc/supervisord.conf
  tags: supervisor
