  - name: Set admin group
    group: name=admin state=present

  - name: Set user for Rudolf Kreibich
    user: name=rudolf group=admin groups=wheel createhome=yes comment='Rudolf Kreibich' password="{{ item }}"
    with_file:
    - ../shared/encrypted/rudolf

  - name: Set public key for Rudolf Kreibich
    authorized_key: user=rudolf key="{{ item }}"
    with_file:
    - ../shared/public_keys/rudolf

  - name: Set user Bystroushaak
    user: name=bystroushaak group=admin groups=wheel createhome=yes comment='J.S.'

  - name: Set public key for Bystroushaak
    authorized_key: user=bystroushaak key="{{ item }}"
    with_file:
    - ../shared/public_keys/bystroushaak

  - name: Set user for Jaroslav Kvasnica
    user: name=jara group=admin groups=wheel createhome=yes comment='Jaroslav Kvasnica'
