# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Customize virtualbox configuration
  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "512"]
  end

  config.vm.box = "bento/centos-7.2"
  config.ssh.insert_key = true

  {
    'vagrant00'	=> '192.168.200.10',
#    'vagrant01'	=> '192.168.200.11',
#    'vagrant02'	=> '192.168.200.12',
#    'vagrant03'  => '192.168.60.23',
  }.each do |short_name, ip|
      config.vm.define short_name do |host|
        host.vm.network 'private_network', ip: ip
        host.vm.hostname = "#{short_name}.webarchiv.cz"
      end
  end

   # Individual host configuration
#  config.vm.define "template" do |host|
#    host.vm.network :forwarded_port, guest: 80, host: 2180
#  end

  # Provisioning with Ansible
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "site.yml"
  end
end
