---
  - name: CZIDLO | /opt/czidlo exists
    file: path="/opt/czidlo" state="directory"

  - name: CZIDLO | Download and extract CZIDLO 4.3.alpha
    unarchive:
      src="https://github.com/NLCR/CZIDLO/releases/download/v4.3.alpha/CZIDLO_4.3.alpha-installation.zip.zip"
      dest="/opt/czidlo/"
      copy="no"
      creates="/opt/czidlo/README.TXT" # Very dirty way to make this task run only once

  - name: CZIDLO | psycopg2 is intalled
    yum: name="python-psycopg2" state="installed"

  - name: CZIDLO | Database resolver is created
    postgresql_db: name="resolver"
    become: true
    become_user: "postgres"
    register: "resolver_created"

  - name: CZIDLO | init PostgreSQL database with CZIDLO script
    command: psql -d resolver -a -f /opt/czidlo/initDatabase_4.3.alpha.sql # Not sure if -a is needed
    become_user: "postgres"
    when: "resolver_created.changed"

  - name: CZIDLO | Configure Tomcat context.xml
    template:
      src: templates/context.xml.j2
      dest: /etc/tomcat/context.xml
      owner: tomcat
      group: tomcat
      mode: 0664
    notify:
    - restart tomcat

  - name: CZIDLO | Deploy API into Tomcat
    command: cp /opt/czidlo/api-4.3.alpha.war /var/lib/tomcat/webapps/api.war
             creates="/var/lib/tomcat/webapps/api/WEB-INF/classes/api.properties"

  - name: CZIDLO | Configure API
    template:
      src: "templates/api.properties.jp2"
      dest: "/var/lib/tomcat/webapps/api/WEB-INF/classes/api.properties"
      owner: "tomcat"
      group: "tomcat"
      mode: "0644"
    notify:
    - restart tomcat

  - name: CZIDLO | Deploy WEB into Tomcat
    command: cp /opt/czidlo/web-4.3.alpha.war /var/lib/tomcat/webapps/web.war
             creates="/var/lib/tomcat/webapps/WEB-INF/classes/web.properties"

  - name: CZIDLO | Configure WEB
    template:
      src: "templates/api.properties.jp2"
      dest: "/var/lib/tomcat/webapps/web/WEB-INF/classes/web.properties"
      owner: "tomcat"
      group: "tomcat"
      mode: "0644"
    notify:
    - restart tomcat

  - name: CZIDLO | Deploy processDataServer into Tomcat
    command: cp /opt/czidlo/processDataServer-4.3.alpha.war /var/lib/tomcat/webapps/processDataServer.war
             creates="/var/lib/tomcat/webapps/processDataServer/WEB-INF/classes/processDataServer.properties"

  - name: CZIDLO | Configure ProcessDataServe
    template:
      src: "templates/processDataServer.properties.j2"
      dest: "/var/lib/tomcat/webapps/processDataServer/WEB-INF/classes/processDataServer.properties"
      owner: "tomcat"
      group: "tomcat"
      mode: "0644"
    notify:
    - restart tomcat

  - name: CZIDLO | Deploy OAI into Tomcat
    command: cp /opt/czidlo/oaiPmhProvider-4.3.alpha.war /var/lib/tomcat/webapps/oaiPmhProvider.war
             creates="/var/lib/tomcat/webapps/oaiPmhProvider/WEB-INF/classes/oaiPmhProvider.properties"

  - name: CZIDLO | Configure API
    template:
      src: "templates/oaiPmhProvider.properties.jp2"
      dest: "/var/lib/tomcat/webapps/oaiPmhProvider/WEB-INF/classes/oaiPmhProvider.properties"
      owner: "tomcat"
      group: "tomcat"
      mode: "0644"
    notify:
    - restart tomcat
