---
  - name: CZIDLO | /opt/czidlo exists
    file: path="/opt/czidlo" state="directory"

  - name: CZIDLO | Download and extract CZIDLO 4.3.alpha
    unarchive:
      src="https://github.com/NLCR/CZIDLO/releases/download/v4.3.alpha/CZIDLO_4.3.alpha-installation.zip.zip"
      dest="/opt/czidlo/"
      copy="no"
      creates="/opt/czidlo/README.TXT" # Very dirty way to make this task run only once

  - name: CZIDLO | psycopg2 is intalled
    yum: name="python-psycopg2" state="installed"

  - name: CZIDLO | Database resolver is created
    postgresql_db: name="resolver"
    become: true
    become_user: "postgres"
    register: "resolver_created"

  - name: CZIDLO | init PostgreSQL database with CZIDLO script
    command: psql -d resolver -a -f /opt/czidlo/initDatabase_4.3.alpha.sql # Not sure if -a is needed
    become_user: "postgres"
    when: "resolver_created.changed"

  - name: CZIDLO | Grant access to Resolver database
    postgresql_user: db="resolver" name="resolver" password="password" priv="ALL"
    become_user: "postgres"

  - name: CZIDLO | Configure Tomcat context.xml
    template:
      src: "templates/context.xml.j2"
      dest: "/etc/tomcat/context.xml"
      owner: "tomcat"
      group: "tomcat"
      mode: "0664"
    notify:
    - restart tomcat

  - name: CZIDLO | Deploy API WAR
    command: cp /opt/czidlo/api-4.3.alpha.war /var/lib/tomcat/webapps/api.war
             creates="/var/lib/tomcat/webapps/api/WEB-INF/classes/api.properties"

  - name: CZIDLO | Deploy API template
    template:
      src: "templates/api.properties.j2"
      dest: "/var/lib/tomcat/webapps/api/WEB-INF/classes/api.properties"
      owner: "tomcat"
      group: "tomcat"
      mode: "0644"
    notify:
    - restart tomcat

  - name: CZIDLO | Deploy WEB WAR
    command: cp /opt/czidlo/web-4.3.alpha.war /var/lib/tomcat/webapps/web.war
             creates="/var/lib/tomcat/webapps/web/WEB-INF/classes/web.properties"

  - name: CZIDLO | Deploy WEB template
    template:
      src: "templates/web.properties.j2"
      dest: "/var/lib/tomcat/webapps/web/WEB-INF/classes/web.properties"
      owner: "tomcat"
      group: "tomcat"
      mode: "0644"
    notify:
    - restart tomcat

  - name: CZIDLO | Deploy WEB hibernate.cfg.xml
    template:
      src: "templates/hibernate.cfg.xml.j2"
      dest: "/var/lib/tomcat/webapps/web/WEB-INF/classes/hibernate.cfg.xml"
      owner: "tomcat"
      group: "tomcat"
      mode: "0644"
    notify:
    - restart tomcat

  - name: CZIDLO | Deploy processDataServer WAR
    command: cp /opt/czidlo/processDataServer-4.3.alpha.war /var/lib/tomcat/webapps/processDataServer.war
             creates="/var/lib/tomcat/webapps/processDataServer/WEB-INF/classes/processDataServer.properties"

  - name: CZIDLO | Deploy processDataServer template
    template:
      src: "templates/processDataServer.properties.j2"
      dest: "/var/lib/tomcat/webapps/processDataServer/WEB-INF/classes/processDataServer.properties"
      owner: "tomcat"
      group: "tomcat"
      mode: "0644"
    notify:
    - restart tomcat

  - name: CZIDLO | Deploy processDataServer hibernate.cfg.xml
    template:
      src: "templates/hibernate.cfg.xml.j2"
      dest: "/var/lib/tomcat/webapps/processDataServer/WEB-INF/classes/hibernate.cfg.xml"
      owner: "tomcat"
      group: "tomcat"
      mode: "0644"
    notify:
    - restart tomcat

  - name: CZIDLO | Deploy OAI WAR
    command: cp /opt/czidlo/oaiPmhProvider-4.3.alpha.war /var/lib/tomcat/webapps/oaiPmhProvider.war
             creates="/var/lib/tomcat/webapps/oaiPmhProvider/WEB-INF/classes/oaiPmhProvider.properties"

  - name: CZIDLO | Deploy OAI template
    template:
      src: "templates/oaiPmhProvider.properties.j2"
      dest: "/var/lib/tomcat/webapps/oaiPmhProvider/WEB-INF/classes/oaiPmhProvider.properties"
      owner: "tomcat"
      group: "tomcat"
      mode: "0644"
    notify:
    - restart tomcat
