---
- name: EPEL repository installed
  yum: name="epel-release"

- name: Nginx installed
  yum: name="nginx"

- name: Self-signed certificate ready
  command: 'openssl req -x509 -nodes -days 365 -newkey rsa:2048 -subj "/C=CZ/ST=Prague/L=Klementinum/O=NLCR/CN=rudolf.kreibich@nkp.cz" -keyout /etc/nginx/nginx-{{ ansible_fqdn }}.key -out /etc/nginx/nginx-{{ ansible_fqdn }}.crt'
  args:
    creates: '/etc/nginx/nginx.crt'
  notify: reload nginx
  tags: nginx

- name: configuration is present
  template: src="{{ item.src }}" dest="{{ item.dest }}"
  with_items:
    - { src: "nginx.conf.j2", dest: "/etc/nginx/nginx.conf" }
  tags: nginx,config
  notify: reload nginx

- name: Nginx survives restarts
  service: name="nginx" enabled="yes" state="running"
...
